### ISSUE TITLE
"My Account" Navbar tooltips

### ISSUE THREAD

**Issue by brysonreece** [OULibraries/oulib_bootstrap#132]
Database & E-Reference and New Search tooltips follow improper grammatical structure and spelling.

**Comment by brysonreece** [comment]
To clarify, this is an issue visible by clicking "Advanced Search" from the libraries homepage, then hovering over "Databases and E-Reference" and "New Search" while on Ex Libris.

**Comment by tdpearson** [comment]
@brysonreece The Ex Libris site is an external 3rd party and out of scope for this repository. I hope that you received a response prior to this message. I will be closing this issue.
